[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.8"
bcrypt = "0.17.1"
config = "0.15.19"
dotenvy = "0.15.7"
hyper = "1.8.1"
rand = "0.9.2"
rumqttd = "0.20.0"
rusqlite = "0.38.0"
serde = "1.0.228"
thread = "0.0.1"
tokio = "1.48.0"
uuid = "1.19.0"
